jwt:
  secret: 'dummy'

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usermanagement
    password: admin
    username: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect